AWSTemplateFormatVersion: '2010-09-09'
Description: A scheduled Amazon Lambda function to delete stale tweets.
Parameters:
  NeuralyzerTweetAgeThreshold:
    Default: 2190h
    Description: The age threshold of a tweets to be deleted.
    Type: String
Resources:
  NeuralyzerFunction:
    Properties:
      CodeUri: .
      Environment:
        Variables:
          NEURALYZER_TWEET_AGE_THRESHOLD:
            Ref: NeuralyzerTweetAgeThreshold
      Events:
        Neuralize:
          Properties:
            Schedule: rate(1 day)
          Type: Schedule
      Handler: main
      Role:
        Fn::GetAtt:
        - NeuralyzerRole
        - Arn
      Runtime: go1.x
    Type: AWS::Serverless::Function
  NeuralyzerRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyDocument:
          Statement:
          - Action: ssm:GetParameter*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/neuralyzer*
          Version: '2012-10-17'
        PolicyName: ParameterStoreAccess
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
